export const ADD_JOURNAL_ENTRY_REQUEST = "ADD_JOURNAL_ENTRY_REQUEST"
export const ADD_JOURNAL_ENTRY_SUCCESS = "ADD_JOURNAL_ENTRY_SUCCESS"
export const ADD_JOURNAL_ENTRY_ERROR = "ADD_JOURNAL_ENTRY_ERROR"

export const GET_TRIAL_BALANCE_REQUEST = "GET_TRIAL_BALANCE_REQUEST"
export const GET_TRIAL_BALANCE_SUCCESS = "GET_TRIAL_BALANCE_SUCCESS"
export const GET_TRIAL_BALANCE_ERROR = "GET_TRIAL_BALANCE_ERROR"

export const GET_INCOME_STATEMENT_REQUEST = "GET_INCOME_STATEMENT_REQUEST"
export const GET_INCOME_STATEMENT_SUCCESS = "GET_INCOME_STATEMENT_SUCCESS"
export const GET_INCOME_STATEMENT_ERROR = "GET_INCOME_STATEMENT_ERROR"

export const GET_BALANCE_REQUEST = "GET_BALANCE_REQUEST"
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS"
export const GET_BALANCE_ERROR = "GET_BALANCE_ERROR"

export const GET_OWNER_EQUITY_REQUEST = "GET_OWNER_EQUITY_REQUEST"
export const GET_OWNER_EQUITY_SUCCESS = "GET_OWNER_EQUITY_SUCCESS"
export const GET_OWNER_EQUITY_ERROR = "GET_OWNER_EQUITY_ERROR"

