export const ADD_JOURNAL_ENTRY_REQUEST = "ADD_JOURNAL_ENTRY_REQUEST"
export const ADD_JOURNAL_ENTRY_SUCCESS = "ADD_JOURNAL_ENTRY_SUCCESS"
export const ADD_JOURNAL_ENTRY_ERROR = "ADD_JOURNAL_ENTRY_ERROR"

export const GET_TRIAL_BALANCE_REQUEST = "GET_TRIAL_BALANCE_REQUEST"
export const GET_TRIAL_BALANCE_SUCCESS = "GET_TRIAL_BALANCE_SUCCESS"
export const GET_TRIAL_BALANCE_ERROR = "GET_TRIAL_BALANCE_ERROR"



